# Generated by Django 4.1.3 on 2022-11-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App1Categoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=40, unique=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app1_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App1Ciudad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=40, unique=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app1_ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App1Concurso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('concurso', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_max_registro', models.DateField(blank=True, null=True)),
                ('maxpersonas', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('urlimagenlogo', models.CharField(blank=True, db_column='urlImagenLogo', max_length=255, null=True)),
                ('urlimagenoficial', models.CharField(blank=True, db_column='urlImagenOficial', max_length=255, null=True)),
            ],
            options={
                'db_table': 'app1_concurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App1ConcursoPuntaje',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField()),
                ('registro', models.DateTimeField()),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app1_concurso_puntaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App1ConcursoReglas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app1_concurso_reglas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App1Diccionario',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'app1_diccionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App1Empleado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigoempleado', models.IntegerField(db_column='codigoEmpleado', unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('cedula', models.IntegerField(unique=True)),
                ('edad', models.IntegerField()),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app1_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App1Sexo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'app1_sexo',
                'managed': False,
            },
        ),
    ]
