# Generated by Django 4.1.3 on 2022-11-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_app1categoria_app1ciudad_app1concurso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuienEsFesus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
