# Generated by Django 4.1.3 on 2022-11-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_app1concursoinscritos_alter_quienesfesus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='App1ConcursoInscritosPuntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('idusuario', models.IntegerField()),
                ('registro', models.DateTimeField()),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app1_concurso_inscritos_puntaje',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='App1ConcursoPuntaje',
        ),
        migrations.AlterModelTable(
            name='quienesfesus',
            table='App1_quienesfesus',
        ),
    ]
