# Generated by Django 4.1.3 on 2022-11-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_app1concursoinscritospuntaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='App1ConcursoInscritosLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idconcurso', models.IntegerField()),
                ('idempleado', models.IntegerField(blank=True, null=True)),
                ('idcategoria', models.IntegerField(blank=True, null=True)),
                ('cedula', models.IntegerField(blank=True, null=True)),
                ('codigoempleado', models.IntegerField(blank=True, null=True)),
                ('registro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('intentos', models.IntegerField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app1_concurso_inscritos_log',
                'managed': False,
            },
        ),
    ]
